### ISSUE TITLE
Lost control of Insteon devices after 2022.9.5

### ISSUE THREAD

**Issue by rtyk** [pyinsteon/pyinsteon#242]
Not sure exactly what is going on, but after an upgrade to 2022.9.5, I can no longer control my Insteon devices. I have rebooted the Insteon hub and restarted HA multiple times and the problem persisted. I rolled back to 2022.8.7 and the Insteon integration began working again. 
Notes - using Hub V2, Upgrade to 2022.9.5 was my first update to 2022.9.x
This error shows in the log.

`Logger: pyinsteon.protocol.protocol
Source: runner.py:119
First occurred: September 18, 2022 at 11:17:45 PM (10599 occurrences)
Last logged: 2:58:38 PM

pyinsteon transport exception: 'bytes' object has no attribute 'extend'`

**Comment by rtyk** [comment]
The problem has now somehow resolved itself.
